### ISSUE TITLE
Notice information for the users that they need to delete the migrated gallery before they can migrate it again

### ISSUE THREAD

**Issue by Florin415** [WPChill/modula-lite#415]
**Is your feature request related to a problem? Please describe.**
If we create a gallery in FooGallery for example, migrate it to Modula , send it to trash , go to FooGallery make new changes and try to Migrate it again it will show you that the gallery was migrated again but when you go to your galleries it will not appear until you delete it from trash.

**Describe the solution you'd like**
To inform the user that the gallery from trash will not be migrated again or something similar. Encountered this when I was testing FooGallery and Modula migrate, sent to trash the old gallery and wanted to migrate it again with the new settings made in FooGallery . If a user receives this message after the migrate : https://prnt.sc/tdzfk0 , he might think that there is a issue with the migrating option when he will search for his gallery  especially if he will have a lot of galleries in his trash or he will not know what to do in this situation.

Any thought on this @cristianraiber @giucu91 @andyluak @razvanaldea89

**Comment by cristianraiber** [comment]
@Florin415 - good catch :) 
@razvanaldea89 - I think you should check if the gallery status BEFORE trying to import it. A gallery that's currently trashed shouldn't be imported IMHO. CC @giucu91

**Comment by razvanaldea89** [comment]
@cristianraiber A trashed gallery isn't imported again. What @Florin415 is saying is that if an imported gallery is trashed and the users forgets about it or wants to import the gallery again, he/she will go to the migrate section and try to migrate the gallery again, just to be told that the gallery is already migrated and won't know why the migration won't start over, thus the information that trashed galleries ( Modula galleries ) won't be imported again, they need to be deleted ( Modula galleries that correspond to the other plugin's galleries ) in order to make the migration again.

**Comment by Florin415** [comment]
made a demo video : https://drive.google.com/file/d/1qAJmQj0Vc4QJspvMuRgrsO1DCxR5Sah-/view
