### ISSUE TITLE
images are not displayed properly on iPhone

### ISSUE THREAD

**Issue by beatricelucaci** [WPChill/modula-lite#657]
**Describe the bug**
I've noticed that on my iPhone, the last 4 images of the image gallery are not showing properly. These images show moved up, with white space at the bottom. The lightbox does work.
This wasn't a problem when I made the gallery, it showed properly.
https://www.qiuarchitecture.com/projects/the-cube-international-container-arts-festival-kaohsiung-taiwan/

In addition, the page below has issues with most images.
https://www.qiuarchitecture.com/news/the-cube-under-construction/
Not only on mobile, but also on desktop (3rd, 5th-10th image nor showing in overview, but do show in lightbox). This wasn't a problem when I made the gallery, but all of a sudden there is this glitch. The problem has been for a few weeks now, and I have manually updated all plugins to see if that would have been a problem. My only plugin that auto-updates in wordpress itself.

https://secure.helpscout.net/conversation/1879540431/0/?folderId=4656050

* Which browser is affected (or browsers): 
- [ ] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Other 

* Which device is affected (or devices): 
- [x] Desktop
- [ ] Tablet
- [x] Mobile
- [ ] Other

**Comment by TeoAlex** [comment]
The issue comes from this addon(https://wordpress.org/plugins/wp-smartcrop/) witch replaces the entire <img> tag with the one formatted by it. It does this by filtering the_content for any <img> tags.

During the replacement of tags the following changes and errors occur:
- a src attribute is added to the image and this breaks the lazyload event. We dont add a src on images waiting to be lazy loaded.
- the data-full ( and other data-* ) attributes are added back to the image tag but malformed ( data-full -> full ) and this breakes the source for the fancybox image.
